name: Build and Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Action for checking out a repo 
      uses: actions/checkout@v4

    - name: Install Act dependencies
      if: ${{ env.ACT }}
      run: |
        apt-get update && apt-get install sudo -y

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install curl build-essential -y

    - name: Set up GitHub Actions workflow with a specific version of Deno 
      uses: denoland/setup-deno@v1
      with:
        deno-version: rc 

    - name: Setup yt-dlp using setup-yt-dlp
      uses: AnimMouse/setup-yt-dlp@main
      with:
        with-ffmpeg: ${{ matrix.ffmpeg == 'with-ffmpeg' }}
        version: ${{ matrix.version }}
        nightly: ${{ matrix.nightly == 'nightly' }}

    - name: Test yt-dlp-FFmpeg by checking version
      if: matrix.ffmpeg == 'with-ffmpeg'
      run: ffmpeg -version

    - name: Test yt-dlp by checking version
      run: yt-dlp --version

    - name: Compile main.ts
      run: deno compile -NR main.ts -o yt-dlp-hq-${{ runner.os }}

    - name: Create directory
      run: mkdir release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: yt-dlp-hq-${{ runner.os }}
        path: release/yt-dlp-hq-${{ runner.os }}${{ runner.os == 'Windows' && '.exe' || '' }}
